dataset <- read.csv('D:/TugasDM/AssessmentR_Dataset_superstore_simple.csv')
View(dataset)
library(dplyr)
dataset <- read.csv('D:/TugasDM/AssessmentR_Dataset_superstore_simple.csv')
dataset_1 <- dataset %>% select(customer_id,sales) %>% filter(sales == max(sales))
dataset_2 <- dataset %>% select(category, sub_category,profit) %>% filter(category == 'Office Supplies')
dataset_3 <- nrow(dataset %>% select(profit) %>% filter(profit < 0))
dataset_5 <- dataset %>%  filter(customer_id %in% c("JE-16165","KH-16510","AD-10180")) %>% group_by(customer_id) %>% summarise(total_sales=sum(sales))
dataset_4 <- dataset %>%  select(customer_id,sales) %>% filter(customer_id %in% c("JE-16165","KH-16510","AD-10180")) %>% group_by(customer_id) %>% summarise(total_sales=sum(sales)) %>% filter(total_sales == max(total_sales))
yearly_sales <- dataset %>% group_by(customer_id) %>% summarise(total_sales=sum(sales))                                                        